#credentials

[credentials.usernames.fsambugaro]
name = "Fabio Sambugaro"
email = "fsambuga@adobe.com"
password = "$2b$12$GAulYOsRCZd7uyThqBQ4OOBTEKuQpUnhti2j8kHbyopk7akyMA3sW"

# … repita para cada usuário …

[clari]
token = "05968116-4f82-4bd7-95aa-56d2b836fee8142675-0"
base_url = "https://api.clari.com"
report_id = "68154b1c2385aa673b611594"

[cookie]
name = "latam_dashboard"
key = "uma_chave_secreta_longaealeatoria"
expiry_days = 1

[preauthorized]
emails = ["fsambuga@adobe.com"]
